---
- name: Converge
  hosts: all
  become: true
  pre_tasks:
    - name: Gather facts
      ansible.builtin.setup:

    - name: Install BIND
      tags: [install]
      ansible.builtin.include_role:
        name: amigus.bind
        tasks_from: install

  roles:
    - role: amigus.bind

  tasks:
    - name: Install RPZ update scripts and cron jobs
      ansible.builtin.include_role:
        name: amigus.bind
        tasks_from: rpz-scripts
