---
- name: Configure a BIND server
  hosts: bind
  pre_tasks:
    - name: Install BIND
      tags: [install]
      ansible.builtin.include_role:
        name: amigus.bind
        tasks_from: install
  roles:
    - role: amigus.bind
  vars:
    bind_forwarders: [1.1.1.1, 9.9.9.9]
    bind_forward_only: true

